development:
  environment: "sandbox"
  username: "store_1233166355_biz_api1.thirdmode.com"
  password: "ASTAK9LM53T7Z67R"
  signature: "AwxegZkzaWUo3THI-xmZGuDkRQFkAFIYbjWj0Q1F6lb-5GEonTuxt.7W"
  application_id: "APP-80W284485P519543T"
  ssl_cert_file: "/opt/tmstore/security/cacert.pem"

test:
  environment: "sandbox"
  username: "store_1233166355_biz_api1.thirdmode.com"
  password: "ASTAK9LM53T7Z67R"
  signature: "AwxegZkzaWUo3THI-xmZGuDkRQFkAFIYbjWj0Q1F6lb-5GEonTuxt.7W"
  application_id: "APP-80W284485P519543T"
  ssl_cert_file: "/opt/tmstore/securitycacert.pem"

production:
  environment: "production"
  username: "my_production_username"
  password: "my_production_password"
  signature: "my_production_signature"
  application_id: "my_production_app_id"
  ssl_cert_file:

with_erb_tags:
  environment: "sandbox"
  username: <%= ENV['paypal.username'] %>
  password: <%= ENV['paypal.password'] %>
  signature: "signupforuseratsandboxpaypal"
  application_id: "APP-TEST"
  ssl_cert_file: